title: Bruno Trentini
description: A space for thoughts and experiments
theme: just-the-docs

color_scheme: dark
favicon_ico: "/assets/images/biology.png"
logo: "/assets/images/biology.png"

callouts:
  warning:
    title: Warning
    color: red

url: https://github.com/btrentini?tab=repositories
