title: Bruno Trentini
description: A space for thoughts and experiments
theme: just-the-docs

color_scheme: dark
favicon_ico: "/assets/images/biology.png"



url: https://github.com/btrentini?tab=repositories
