#!/usr/bin/env python3
"""Build the static manifest for every PDF in ./tarchic-charts."""

from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "tarchic-charts"
OUTPUT = ROOT / "website" / "data" / "tarchic_chart_manifest.js"


def human_title(stem: str) -> str:
    text = stem
    for prefix in (
        "figures__",
        "added_analysis__",
        "edm_ode_heun_",
        "edm_sde_heun_",
        "atlas_alphaflow_",
        "cameo_alphaflow_",
        "alphaflow_",
    ):
        if text.startswith(prefix):
            text = text[len(prefix):]
            break
    text = text.replace("_", " ").replace("condmarg", "cond-marg")
    text = text.replace("fid", "FID").replace("nfe", "NFE").replace("plddt", "pLDDT")
    text = text.replace("rmsd", "RMSD").replace("edm", "EDM")
    return " ".join(part.capitalize() if part.islower() and len(part) > 3 else part for part in text.split())


def first_note(pdf: Path) -> str:
    txt = pdf.with_suffix(".txt")
    if not txt.exists():
        return ""
    for line in txt.read_text(encoding="utf-8", errors="replace").splitlines():
        clean = line.strip()
        if clean:
            return clean
    return ""


def classify(parts: tuple[str, ...]) -> dict[str, str]:
    root = parts[0] if parts else ""
    run = "run40" if "run40" in root else "run41" if "run41" in root else "before run38"
    domain = "EDM" if "edm" in root else "AlphaFlow" if "alphaflow" in root else "Theory"
    scope = parts[1] if len(parts) > 1 else "shared"
    collection = next((part for part in parts if part in {"tarchic", "exploratory", "scoped_pdf_evidence"}), "tarchic")
    nfe = next((part for part in parts if part.startswith("nfe_")), "")
    size = next((part for part in parts if part in {"short", "medium", "large"}), "")
    scope_label = {
        "ode": "ODE",
        "sde": "SDE",
        "atlas": "ATLAS",
        "cameo": "CAMEO",
        "shared_scheduler": "shared scheduler",
        "shared_schedule": "shared schedule",
    }.get(scope, scope.replace("_", " "))
    category_parts = [domain, scope_label, collection.replace("_", " ")]
    if nfe:
        category_parts.append(nfe.replace("_", " ").upper())
    if size:
        category_parts.append(size)
    return {
        "run": run,
        "domain": domain,
        "scope": scope_label,
        "collection": collection.replace("_", " "),
        "category": " / ".join(category_parts),
    }


def main() -> None:
    charts = []
    for pdf in sorted(SOURCE.rglob("*.pdf")):
        rel = pdf.relative_to(SOURCE)
        parts = rel.parts
        fields = classify(parts)
        href = f"tarchic-charts/{rel.as_posix()}"
        charts.append(
            {
                **fields,
                "title": human_title(pdf.stem),
                "href": href,
                "source_path": f"tarchic-charts/{rel.as_posix()}",
                "note": first_note(pdf),
            }
        )

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    payload = json.dumps(charts, indent=2, ensure_ascii=True)
    OUTPUT.write_text(
        "// Generated by website/scripts/build_tarchic_chart_manifest.py\n"
        f"window.TARCHIC_CHART_MANIFEST = {payload};\n",
        encoding="utf-8",
    )
    print(f"Wrote {len(charts)} tarchic chart entries to {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
